name: CI
on:
  push:

defaults:
  run:
    shell: bash

permissions:
  contents: write

# Cancel any in-flight jobs for the same PR/branch so there's only one active
# at a time
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: npm install
    - run: rm .gitignore
    - name: Deploy to gh-pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: .
        single-commit: true
        clean: true
      if: github.ref == 'refs/heads/main'
